name: Issue information
on: 
    issues:
        types: closed
jobs:
    info:
        runs-on: windows-latest
        steps:
          - name: Issue with github context
            run: echo '${{ toJSON(github.event.issue.comments) }}'
          - name: display print
            run: echo "Printed the events"
