name: deploy lint test
on: push
jobs:
    deploy:
        runs-on: windows-latest
        steps: 
            - name: Get Code from repo
              uses: actions/checkout@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy
              run: echo "deploying..."
    lint: 
        runs-on: windows-latest
        needs: deploy
        steps: 
            - name: Get Code from repo
              uses: actions/checkout@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: run lint
              run: npm run lint
            - name: lint
              run: echo "Executing Lint...."          
    test: 
        runs-on: windows-latest
        needs: lint
        steps: 
            - name: Get Code from repo
              uses: actions/checkout@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: run tests
              run: npm test
            - name: Tests
              run: echo "Running the Tests...."
    